"""
LLMExplanation Model

Stores the explanation and recommendations generated by the local LLM
(Ollama → Llama 3.1 / Qwen3) from the detection evidence.

The LLM does NOT generate detection results — it only explains
findings produced by the detection pipeline.
"""

from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.core.database import Base


class LLMExplanation(Base):
    __tablename__ = "llm_explanations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    analysis_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False, unique=True
    )

    # Which LLM model was used
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # Human-readable explanation of findings
    explanation: Mapped[str] = mapped_column(Text, nullable=False)

    # Summary of the analysis
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Recommended actions
    recommendations: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # Risk explanation
    risk_explanation: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Raw LLM response (for debugging and audit)
    raw_response: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Processing time in seconds
    processing_time_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )

    # Relationships
    analysis = relationship("Analysis", back_populates="llm_explanation")

    def __repr__(self) -> str:
        return f"<LLMExplanation(id={self.id}, model={self.model_name})>"
